sudo: required
services:
  - docker

before_install:
  - docker run -e CI=true joaolbaptista2/react-test -f./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true joaolbaptista2/react-test npm test

after_success:
  - docker build -t joaolbaptista2/multi-client ./client
  - docker build -t joaolbaptista2/multi-nginx ./nginx
  - docker build -t joaolbaptista2/multi-server ./server
  - docker build -t joaolbaptista2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push joaolbaptista2/multi-client
  - docker push joaolbaptista2/multi-nginx
  - docker push joaolbaptista2/multi-server
  - docker push joaolbaptista2/multi-worker